// Code generated by protoc-gen-codeactor. DO NOT EDIT.
// CodeActor Agent Events v1.0.0

package protocol

import (
	"encoding/json"
	"fmt"
)

// ===== 事件类型常量 =====
const (
  EventTypeModelInfo EventType = "model_info"
  EventTypeLlmCallStart EventType = "llm_call_start"
  EventTypeLlmCallEnd EventType = "llm_call_end"
  EventTypeAiResponse EventType = "ai_response"
  EventTypeToolCallStart EventType = "tool_call_start"
  EventTypeToolCallResult EventType = "tool_call_result"
  EventTypeToolCallError EventType = "tool_call_error"
  EventTypeContextLoaded EventType = "context_loaded"
  EventTypeCommitContextLoaded EventType = "commit_context_loaded"
  EventTypeAiStreamStart EventType = "ai_stream_start"
  EventTypeAiChunk EventType = "ai_chunk"
  EventTypeAiStreamEnd EventType = "ai_stream_end"
  EventTypeUserHelpNeeded EventType = "user_help_needed"
  EventTypeUserHelpResponse EventType = "user_help_response"
  EventTypeConversationError EventType = "conversation_error"
  EventTypeConversationResult EventType = "conversation_result"
  EventTypeStatusUpdate EventType = "status_update"
  EventTypeThinking EventType = "thinking"
  EventTypeTaskComplete EventType = "task_complete"
)

// EventType 是事件类型的字符串枚举
type EventType string

// String 返回事件类型的字符串表示
func (e EventType) String() string { return string(e) }

// ===== 事件数据类型 =====

// ModelInfoData LLM 模型信息
type ModelInfoData struct {
  Model string `json:"model"` // 模型名称（如 claude-3-5-sonnet）
  Agent string `json:"agent"` // 当前 Agent 名称
  Provider string `json:"provider,omitempty"` // LLM 提供商
}

// LlmCallStartData LLM 调用开始
type LlmCallStartData struct {
  Model string `json:"model"` // 模型名称
  Agent string `json:"agent"` // 发起调用的 Agent 名称
}

// LlmCallEndData LLM 调用结束
type LlmCallEndData struct {
  Model string `json:"model"` // 模型名称
  Agent string `json:"agent"` // Agent 名称
  DurationSeconds float64 `json:"duration_seconds,omitempty"` // 调用耗时（秒）
  Error string `json:"error,omitempty"` // 错误信息（如果有）
}

// AiResponseData AI 响应内容（流式或一次性）
type AiResponseData struct {
  Content string `json:"content"` // AI 生成的文本内容
  Usage json.RawMessage `json:"usage,omitempty"` // Token 使用统计
}

// ToolCallStartData 工具调用开始
type ToolCallStartData struct {
  ToolName string `json:"tool_name"` // 工具名称（如 delegate_repo, delegate_coding）
  Arguments string `json:"arguments"` // 工具调用参数的 JSON 字符串
  ToolCallId string `json:"tool_call_id"` // 工具调用唯一标识
}

// ToolCallResultData 工具调用结果
type ToolCallResultData struct {
  ToolName string `json:"tool_name"` // 工具名称
  Result string `json:"result"` // 工具执行结果文本
  ToolCallId string `json:"tool_call_id"` // 工具调用唯一标识
}

// ToolCallErrorData 工具调用错误
type ToolCallErrorData struct {
  ToolName string `json:"tool_name"` // 工具名称
  Error string `json:"error"` // 错误信息
  ToolCallId string `json:"tool_call_id"` // 工具调用唯一标识
  Arguments string `json:"arguments,omitempty"` // 导致错误的参数
}

// ContextLoadedData 项目上下文加载完成
type ContextLoadedData struct {
  FileCount float64 `json:"file_count"` // 加载的文件数量
  Files []json.RawMessage `json:"files,omitempty"` // 加载的文件列表
}

// CommitContextLoadedData Commit 学习器上下文加载
type CommitContextLoadedData struct {
  CommitCount float64 `json:"commit_count"` // 加载的 commit 数量
}

// AiStreamStartData AI 流式响应开始
type AiStreamStartData struct {
  Agent string `json:"agent"` // Agent 名称
}

// AiChunkData AI 流式响应数据块
type AiChunkData struct {
  Content string `json:"content"` // 文本块
  Agent string `json:"agent,omitempty"` // Agent 名称
}

// AiStreamEndData AI 流式响应结束
type AiStreamEndData struct {
  Agent string `json:"agent"` // Agent 名称
  Usage json.RawMessage `json:"usage,omitempty"` // Token 使用统计（可选）
}

// UserHelpNeededData 需要用户帮助/确认
type UserHelpNeededData struct {
  Question string `json:"question"` // 向用户提出的问题
  Context string `json:"context,omitempty"` // 附加上下文信息
}

// UserHelpResponseData 用户回复了帮助请求
type UserHelpResponseData struct {
  Response string `json:"response"` // 用户的回复内容
  Approved bool `json:"approved,omitempty"` // 是否批准
}

// ConversationErrorData 对话处理错误
type ConversationErrorData struct {
  TaskId string `json:"task_id"` // 任务 ID
  Error string `json:"error"` // 错误描述
}

// ConversationResultData 对话任务完成
type ConversationResultData struct {
  TaskId string `json:"task_id"` // 任务 ID
  Result string `json:"result"` // 最终结果文本
}

// StatusUpdateData 通用状态更新
type StatusUpdateData struct {
  Status string `json:"status"` // 状态描述
  Progress float64 `json:"progress,omitempty"` // 进度百分比（0-100）
}

// ThinkingData Agent 思考过程（推理过程）
type ThinkingData struct {
  Content string `json:"content"` // 思考内容
  Agent string `json:"agent,omitempty"` // Agent 名称
}

// TaskCompleteData 任务完成通知
type TaskCompleteData struct {
  TaskId string `json:"task_id"` // 任务 ID
  Status string `json:"status"` // 完成状态
  Summary string `json:"summary,omitempty"` // 任务摘要
}

// AgentEventEnvelope 是 WebSocket 传输的统一消息包裹
type AgentEventEnvelope struct {
  Type string `json:"type"`
  Event string `json:"event"`
  Data json.RawMessage `json:"data"`
  From string `json:"from,omitempty"`
  TaskId string `json:"task_id,omitempty"`
  Message string `json:"message,omitempty"`
}

// EventTypeRegistry 事件类型到其结构的映射
var EventTypeRegistry = map[EventType]func() interface{}{
  EventTypeModelInfo: func() interface{} { return &ModelInfoData{} },
  EventTypeLlmCallStart: func() interface{} { return &LlmCallStartData{} },
  EventTypeLlmCallEnd: func() interface{} { return &LlmCallEndData{} },
  EventTypeAiResponse: func() interface{} { return &AiResponseData{} },
  EventTypeToolCallStart: func() interface{} { return &ToolCallStartData{} },
  EventTypeToolCallResult: func() interface{} { return &ToolCallResultData{} },
  EventTypeToolCallError: func() interface{} { return &ToolCallErrorData{} },
  EventTypeContextLoaded: func() interface{} { return &ContextLoadedData{} },
  EventTypeCommitContextLoaded: func() interface{} { return &CommitContextLoadedData{} },
  EventTypeAiStreamStart: func() interface{} { return &AiStreamStartData{} },
  EventTypeAiChunk: func() interface{} { return &AiChunkData{} },
  EventTypeAiStreamEnd: func() interface{} { return &AiStreamEndData{} },
  EventTypeUserHelpNeeded: func() interface{} { return &UserHelpNeededData{} },
  EventTypeUserHelpResponse: func() interface{} { return &UserHelpResponseData{} },
  EventTypeConversationError: func() interface{} { return &ConversationErrorData{} },
  EventTypeConversationResult: func() interface{} { return &ConversationResultData{} },
  EventTypeStatusUpdate: func() interface{} { return &StatusUpdateData{} },
  EventTypeThinking: func() interface{} { return &ThinkingData{} },
  EventTypeTaskComplete: func() interface{} { return &TaskCompleteData{} },
}

// RenderHint 包含前端渲染提示
type RenderHint struct {
  Component string `json:"component,omitempty"`
  Heading string `json:"heading,omitempty"`
  ShowHeader bool `json:"show_header,omitempty"`
  Collapse bool `json:"collapse,omitempty"`
  StreamMode bool `json:"stream_mode,omitempty"`
  MergeConsecutive bool `json:"merge_consecutive,omitempty"`
  MaxPreviewLines int `json:"max_preview_lines,omitempty"`
}

// EventRenderHints 事件类型到渲染提示的映射
var EventRenderHints = map[EventType]RenderHint{
  EventTypeAiResponse: {
    Component: "StreamingText",
    Heading: "AI 响应",
  },
  EventTypeToolCallStart: {
    Component: "ToolCallCard",
    Heading: "工具调用",
  },
  EventTypeToolCallResult: {
    Component: "ToolResultCard",
    Heading: "工具结果",
  },
  EventTypeToolCallError: {
    Component: "ToolCallErrorCard",
    Heading: "工具错误",
  },
  EventTypeContextLoaded: {
    Component: "StatusPill",
    Heading: "上下文",
  },
  EventTypeCommitContextLoaded: {
    Component: "StatusPill",
    Heading: "Commit",
  },
  EventTypeAiStreamStart: {
    Component: "StreamingText",
  },
  EventTypeAiChunk: {
    Component: "StreamingText",
  },
  EventTypeAiStreamEnd: {
    Component: "StreamingText",
  },
  EventTypeUserHelpNeeded: {
    Component: "UserConfirmCard",
    Heading: "需要确认",
  },
  EventTypeUserHelpResponse: {
    Component: "StatusPill",
    Heading: "用户回复",
  },
  EventTypeConversationError: {
    Component: "ErrorCard",
    Heading: "错误",
  },
  EventTypeConversationResult: {
    Component: "ResultCard",
    Heading: "任务结果",
  },
  EventTypeStatusUpdate: {
    Component: "StatusPill",
    Heading: "状态",
  },
  EventTypeThinking: {
    Component: "ThinkingCard",
    Heading: "思考过程",
  },
  EventTypeTaskComplete: {
    Component: "TaskCompleteCard",
    Heading: "任务完成",
  },
}

// ParseAgentEvent 根据 event 类型解析 Data 到对应结构
func ParseAgentEvent(envelope AgentEventEnvelope) (interface{}, error) {
  factory, ok := EventTypeRegistry[EventType(envelope.Event)]
  if !ok {
    return nil, fmt.Errorf("unknown event type: %s", envelope.Event)
  }

  data := envelope.Data
  if len(data) == 0 {
    return factory(), nil
  }

  // 如果 data 是 JSON 字符串 token，先解析为字符串再解析到目标类型
  if data[0] == '"' {
    var str string
    if err := json.Unmarshal(data, &str); err != nil {
      return nil, err
    }
    target := factory()
    if err := json.Unmarshal([]byte(str), target); err != nil {
      return nil, err
    }
    return target, nil
  }

  // 直接反序列化 raw message 到目标类型
  target := factory()
  if err := json.Unmarshal(data, target); err != nil {
    return nil, err
  }
  return target, nil
}
