package main

import (
	"fmt"
	"os"
	"strings"
)

func generateGoTypes(doc ProtocolDocument, outputPath string) {
	var sb strings.Builder

	sb.WriteString("// Code generated by protoc-gen-codeactor. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// %s v%s\n", doc.Protocol.Name, doc.Protocol.Version))
	sb.WriteString("\npackage protocol\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString(")\n\n")

	// 事件类型常量
	sb.WriteString("// ===== 事件类型常量 =====\n")
	sb.WriteString("const (\n")
	for _, et := range doc.EventTypes {
		constName := toCamelCaseUpper(et.Name)
		sb.WriteString(fmt.Sprintf("  EventType%s EventType = \"%s\"\n", constName, et.Name))
	}
	sb.WriteString(")\n\n")

	// 事件类型枚举
	sb.WriteString("// EventType 是事件类型的字符串枚举\n")
	sb.WriteString("type EventType string\n\n")
	sb.WriteString("// String 返回事件类型的字符串表示\n")
	sb.WriteString("func (e EventType) String() string { return string(e) }\n\n")

	// 生成每个事件的数据结构
	sb.WriteString("// ===== 事件数据类型 =====\n\n")
	for _, et := range doc.EventTypes {
		structName := toPascalCase(et.Name) + "Data"
		sb.WriteString(fmt.Sprintf("// %s %s\n", structName, et.Description))
		sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		for _, f := range et.Fields {
			goType := toGoType(f.Type)
			jsonTag := fmt.Sprintf("`json:\"%s\"`", f.Name)
			if !f.Required {
				jsonTag = fmt.Sprintf("`json:\"%s,omitempty\"`", f.Name)
			}
			sb.WriteString(fmt.Sprintf("  %s %s %s // %s\n", toPascalCase(f.Name), goType, jsonTag, f.Description))
		}
		sb.WriteString("}\n\n")
	}

	// 生成包裹结构
	sb.WriteString("// AgentEventEnvelope 是 WebSocket 传输的统一消息包裹\n")
	sb.WriteString("type AgentEventEnvelope struct {\n")
	for _, f := range doc.WebSocketMessage.Fields {
		goType := toGoType(f.Type)
		jsonTag := fmt.Sprintf("`json:\"%s\"`", f.Name)
		if !f.Required {
			jsonTag = fmt.Sprintf("`json:\"%s,omitempty\"`", f.Name)
		}
		sb.WriteString(fmt.Sprintf("  %s %s %s\n", toPascalCase(f.Name), goType, jsonTag))
	}
	sb.WriteString("}\n\n")

	// 生成事件注册表
	sb.WriteString("// EventTypeRegistry 事件类型到其结构的映射\n")
	sb.WriteString("var EventTypeRegistry = map[EventType]func() interface{}{\n")
	for _, et := range doc.EventTypes {
		constName := toCamelCaseUpper(et.Name)
		structName := toPascalCase(et.Name) + "Data"
		sb.WriteString(fmt.Sprintf("  EventType%s: func() interface{} { return &%s{} },\n", constName, structName))
	}
	sb.WriteString("}\n\n")

	// 生成渲染提示映射
	sb.WriteString("// RenderHint 包含前端渲染提示\n")
	sb.WriteString("type RenderHint struct {\n")
	sb.WriteString("  Component string `json:\"component,omitempty\"`\n")
	sb.WriteString("  Heading string `json:\"heading,omitempty\"`\n")
	sb.WriteString("  ShowHeader bool `json:\"show_header,omitempty\"`\n")
	sb.WriteString("  Collapse bool `json:\"collapse,omitempty\"`\n")
	sb.WriteString("  StreamMode bool `json:\"stream_mode,omitempty\"`\n")
	sb.WriteString("  MergeConsecutive bool `json:\"merge_consecutive,omitempty\"`\n")
	sb.WriteString("  MaxPreviewLines int `json:\"max_preview_lines,omitempty\"`\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// EventRenderHints 事件类型到渲染提示的映射\n")
	sb.WriteString("var EventRenderHints = map[EventType]RenderHint{\n")
	for _, et := range doc.EventTypes {
		constName := toCamelCaseUpper(et.Name)
		if et.RenderHint != nil {
			sb.WriteString(fmt.Sprintf("  EventType%s: {\n", constName))
			if et.RenderHint.Component != "" {
				sb.WriteString(fmt.Sprintf("    Component: \"%s\",\n", et.RenderHint.Component))
			}
			if et.RenderHint.Heading != "" {
				sb.WriteString(fmt.Sprintf("    Heading: \"%s\",\n", et.RenderHint.Heading))
			}
			sb.WriteString("  },\n")
		}
	}
	sb.WriteString("}\n\n")

	// JSON 解包辅助函数
	sb.WriteString("// ParseAgentEvent 根据 event 类型解析 Data 到对应结构\n")
	sb.WriteString("func ParseAgentEvent(envelope AgentEventEnvelope) (interface{}, error) {\n")
	sb.WriteString("  factory, ok := EventTypeRegistry[EventType(envelope.Event)]\n")
	sb.WriteString("  if !ok {\n")
	sb.WriteString("    return nil, fmt.Errorf(\"unknown event type: %s\", envelope.Event)\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  data := envelope.Data\n")
	sb.WriteString("  if data == nil {\n")
	sb.WriteString("    return factory(), nil\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  // 如果 Data 是字符串，先解析为 json.RawMessage\n")
	sb.WriteString("  switch v := data.(type) {\n")
	sb.WriteString("  case string:\n")
	sb.WriteString("    target := factory()\n")
	sb.WriteString("    if err := json.Unmarshal([]byte(v), target); err != nil {\n")
	sb.WriteString("      return nil, err\n")
	sb.WriteString("    }\n")
	sb.WriteString("    return target, nil\n")
	sb.WriteString("  default:\n")
	sb.WriteString("    // 先序列化再反序列化到目标类型\n")
	sb.WriteString("    raw, err := json.Marshal(data)\n")
	sb.WriteString("    if err != nil {\n")
	sb.WriteString("      return nil, err\n")
	sb.WriteString("    }\n")
	sb.WriteString("    target := factory()\n")
	sb.WriteString("    if err := json.Unmarshal(raw, target); err != nil {\n")
	sb.WriteString("      return nil, err\n")
	sb.WriteString("    }\n")
	sb.WriteString("    return target, nil\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "写入 Go 类型文件失败: %v\n", err)
		return
	}
	fmt.Printf("  ✓ Go 类型已生成: %s\n", outputPath)
}